### ISSUE TITLE
Info for conf

### ISSUE THREAD

**Issue by Cippo2019** [tomasrudh/analogclock#1]
Hi Tomas
thanks a lot for this analog clock
After installation , we can put info on config file ?
wbr
Cippo

**Comment by tomasrudh** [comment]
Hi Cippo,

I am sorry, I don't quite understand what you mean, can you please explain.

Thanks!
/Tomas

**Comment by TRusselo** [comment]
Code does not go in config. 
Code goes into Lovelace Card.

install repository. 
refresh (ctrl+f5)
go to Overveiw (dashboard).
3 dots menu (top right)
edit dashboard.
Add card (bottom right)
manual card (bottom of list)

Paste code in box.  
```
type: 'custom:analog-clock'
hide_SecondHand: true
locale: EN
diameter: 200
color_HourHand: '#326ba8'
color_MinuteHand: '#3273a8'
color_DigitalTime: '#CCCCCC'
color_FaceDigits: '#a83832'
color_Ticks: Silver
```
Type Spacebar, backspace.  (ui bug wont let you save after paste code.)
click SAVE


![image](https://user-images.githubusercontent.com/1154815/102720050-18efa280-42af-11eb-8617-7bbda2e5eb6b.png)
![image](https://user-images.githubusercontent.com/1154815/102720091-62d88880-42af-11eb-8a9b-eefc76ba729c.png)
![image](https://user-images.githubusercontent.com/1154815/102720275-9e278700-42b0-11eb-96f8-9a436bfaef81.png)

**Comment by tomasrudh** [comment]
Thanks TRusselo for the explanation.

**Comment by Cippo2019** [comment]
Thanks  a lot. I will try as soon as possible..

Scarica Outlook per Android<https://aka.ms/ghei36>

________________________________
