### ISSUE TITLE
53rd week of year?

### ISSUE THREAD

**Issue by nepozs** [tomasrudh/analogclock#10]
![53rd_week_of_year_Screenshot_2021-01-01 Przegląd - Home Assistant](https://user-images.githubusercontent.com/56661567/103432355-d77bc300-4bdd-11eb-9806-a57bbd34c1ef.png)
Maybe it happens only in New Year day?

**Comment by Cippo2019** [comment]
me too.. 53 .. we are still on 2020 :-(

**Comment by tomasrudh** [comment]
I am following ([ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)). Strangely enough, 2020 has 53 weeks, the last week spills over into 2021. Week 1 starts 2021-01-04.
Thanks for reporting!
