### ISSUE TITLE
Colour text weekday

### ISSUE THREAD

**Issue by kenge1967** [tomasrudh/analogclock#12]
Hallå
I can't change the colour of the text for weekdays

BR
Kenneth

**Comment by tomasrudh** [comment]
Hej,
I can't reproduce that, when I set a color using 'color_Text' does that color apply to week day, date and week number. Try to clear the browser cache and let me know if that helps.

/Tomas

**Comment by kenge1967** [comment]
Solved it
I had a lowercase for the letter t in "color_text" I changed to "color_Text" so now it works
Thanks for your time

//Kenneth

**Comment by tomasrudh** [comment]
Ok, very good. Well spotted. And thanks for the coffee :)

/Tomas
