### ISSUE TITLE
Suggestion: Different (background) colors indicating day and night

### ISSUE THREAD

**Issue by jhein05** [tomasrudh/analogclock#13]
This card is amazing. If you are in desperate need for new features ideas, may I suggest a color change that indicates if it is day or night. It would mean to define a day color and a night color, maybe for the background, and it would use day colors from 6 to 18 and night colors for the other half of the day. It would make using the card multiple times as a world clock even more useful. A little bit like GMT wrist watches do it. Example:
![image](https://user-images.githubusercontent.com/5014124/104368148-8d91b780-54d0-11eb-9c0d-68a664c56338.png)

**Comment by tomasrudh** [comment]
Interesting! The picture shows a cock with fixed color fields, I guess? But you mean change the background color at the shift from day to night? One idea could be to, as an alternative to fixed times, change when the sun sets and rises.

**Comment by jhein05** [comment]
Yes, that would be even better, but I guess also get really complicated when using multiple clocks that all have different time zones.

**Comment by jhein05** [comment]
Also, the use case is more "Can I call a person in that time zone right now?". The information if the sun is up or down is less useful in my opinion. Maybe allowing the day/night cutoff times to be configured as well could be a compromise, because that is an individual decision. I would set day from 9 to 20, while other people might want to do it differently, e.g. based on work hours.

**Comment by tomasrudh** [comment]
Yes, you are right, fixed times are probably more useful. I will leave this request for a while to see if anyone else has any additional ideas. Thanks for your time, much appreciated!

**Comment by tomasrudh** [comment]
I just released version 1.6 featuring themes that makes this possible.
