### ISSUE TITLE
Finer grained face control

### ISSUE THREAD

**Issue by parautenbach** [tomasrudh/analogclock#14]
This is the first analogue clock for HA that I actually like. Thanks!

Would it be possible to have an option to have the face text overlay the hands so that the hands appear behind? I think it would be easier to read the text. Alternatively, you could allow for the alpha channel to be specified for the hand colours. 

If one can use theme variables for colours that would be great too. Currently, it's only the background that makes use of a theme colour. You have your own theme option but I think it would be more seamless if theme variables are used, especially where one has an HA instance that automatically changes between a light and dark theme depending on whether the sun's up or down. 

An option to hide the minor ticks would also be useful to someone that wants a more minimalistic look. 

Instead of displaying the timezone, it would be great just to specify your own name or label. This is useful where you specify a timezone but the city or town you have in mind is different.

**Comment by tomasrudh** [comment]
Thanks for your kind words Pieter!

It would be easier to read the text, but I believe it would alter the look from a real clock a little too much. It would to be honest look strange that the text is on top of the hands.

I will for sure consider adding more colors to the theme.

A possibility to hide minor ticks is a good idea.

Also a custom display name for the time zone is a good idea.

Thank you for taking the time to write to me.
/Tomas

**Comment by tomasrudh** [comment]
Just released 1.7 implementing theme for all settings except timezone and diameter. The rest is also implemented, except displaying text above the hands.

**Comment by tomasrudh** [comment]
About having the text in front of the hands, the hands can from version 2.0 be made transparent, to show the text 'through' them.
