### ISSUE TITLE
Suggestions: Configure date format & option for 24/12h digital clock

### ISSUE THREAD

**Issue by jhein05** [tomasrudh/analogclock#15]
I agree with Pieter, that this is the best analog clock for HA.

Just two suggestions, in case you are bored one day :)

1.) It would be nice to be able to configure the way the date is displayed, maybe using strftime syntax like HA does.

2.) An option to configure if the digital time is displayed in 24 or 12 hour format would be great too

Cheers,
Julian

**Comment by tomasrudh** [comment]
Thank you! I will consider your ideas, they are very good.

/Tomas

**Comment by tomasrudh** [comment]
Just released version 1.7 including the above. strftime is unfortunately not available in Javascript, by including moment.js is the functionality implemented. Number 2 is also achieved by using formatting.
