### ISSUE TITLE
Problem with dateformat

### ISSUE THREAD

**Issue by hugodelaroza** [tomasrudh/analogclock#16]
Hi Tomas, thanks for your great job, I´ve been using your card for some moths and haven´t had problems with it untill now. 

The problem I´m havig is this:

I added the resource https://unpkg.com/moment@2.29.1/min/moment-with-locales.js as a JavaScript Module (just module is not an option in my lovelace) and configure the dateformat as the last example (dateformat: "MMM Do YYYY").
When I do this, the clock desappear of my dashboard. I edit the code with the raw editor of lovelace and I see that the editor erases the quotation marks (whenever I use double or simple).
I erase the line with the dateformat option, and the clock appears again. It seems to me that the lovelace editor, I don´t know why, erases the quotation marks every time, therefore the clock desappear

Thank´s for your help!

**Comment by tomasrudh** [comment]
Hi,
I don't think the quotes are the problem, the fact that the hands comes back when you remove the line with dateformat suggests that 'moment' is not properly loaded. When dateformat is removed is 'moment' not expected to be loaded any longer, and thus no problem.
Try to clear your browsers cache, that should do the trick, but it can be a bit stubborn sometimes.

**Comment by tomasrudh** [comment]
Hi again,
You can also try to download moment to a local file, and reference that from Lovelace.

**Comment by hugodelaroza** [comment]
I,ve already done, but didn´t worked. I think the problem is lovelace editor that deletes de quotation marks

**Comment by tomasrudh** [comment]
Maybe, does it work if you set the dateformat to "MMM"?

**Comment by hugodelaroza** [comment]
sorry, same problem...

**Comment by tomasrudh** [comment]
I still think it is a cache problem, I had to try many times before I got it to work. I am actually not sure what did the trick in the end. You can add ?v=2 at the end, to trick the browser it is a new version of the file.
- url: /local/moment_2.29.1-with-locales.js?v=2
I am also not sure if it should be 'js' or 'module'.

**Comment by hugodelaroza** [comment]
I´ll Try later. THANKS for your help!!

**Comment by tallnhairydave** [comment]
Having the same problem, but only in Safari on MacOS. 

downloaded moment-with-locales.js and added it to to the analogclock folder after reinstalling the plugin in HACS, then adding it as a resource to Lovelace dashboards. 

Note that my clock card is not using dateformatting, so should not need to be calling the moment javascript.

```
type: 'custom:analog-clock'
hide_SecondHand: false
hide_digitaltime: false
hide_date: false
hide_weekday: false
style_secondhand: 4
locale: en-GB
diameter: 250
color_HourHand: '#326ba8'
color_MinuteHand: '#3273a8'
color_DigitalTime: '#CCCCCC'
color_FaceDigits: '#a83832'
color_Ticks: Silver

```

**Behaviour in MacOS:**

- In Safari, I get the display with no hands and Invalid Date where the text on the face should be. 
- In Chrome, the clock loads no problems.
- In Firefox, the clock loads no problems. 
 
**Behaviour in mobile Safari on iOS devices:**
- Clock does not display correctly.

Opening the Javascript Console in Safari's developer menu shows that moment-with-locales.js is throwing this error:

**TypeError: undefined is not an object (evaluating 'global.moment = factory()')**

**Comment by tallnhairydave** [comment]
I was thinking "Wonder what happens if I add the  "dateformat:" and "timeformat:" lines given in the examples here to my card YAML.

Would that resolve the "Undefined" issue?

What actually happened was that after saving the card, everything in that view of my dashboard vanished when I loaded the page; and that happened in all three MacOS browsers. 

Removing the dateformat: and timeformat: lines from the raw configuration file for the dashboard restored the card views back to my earlier not above in all three browsers.

Emptying caches has not had any effect in Safari. 

Wonder what browser the OP is using?

**Comment by tallnhairydave** [comment]
Tried adding ?v=2 to the resource in Lovelace resources in HA per advice above. No change to behaviour. 

Only options for the type of resource showing in the Lovelace resources editor are "Javascript Module" or "Stylesheet" so it's got to be set as "Javascript Module".

Restarting Home assistant has no effect. Still broken in Safari on MacOS, but working fine in other MacOS desktop browsers tested.

**Comment by tomasrudh** [comment]
I have tested with Edge and Chrome on Windows, both works fine. It might be that Safari on MacOS has a different version of Javascript, that do not work. Or something that prevents Moment from load. If you want you can try to remove the import of Moment altogether, if you don't have dateformat or timeformat set should the clock work even if Moment is not loaded.

**Comment by tallnhairydave** [comment]
Not seeing anything in the JS that declares an import of the moment-with-locales.js

I've been through the analogclock.js and simply removed the lines where it's referring to moment in the drawtime and drawdate functions, but still get no hands displayed and the words "Invalid Date" where the Digital clock, day of week and date should be displayed. 

again, no timeformat or dateformat set in the YAML. 

Going to try rolling back the JS in my install to the previous commit from here to check if it reverts to normal working.

**Comment by tallnhairydave** [comment]
Weird. Rolled back to the analogclock.js from commit 5958ec, and still having the same behaviour - "Invalid Date" where the text on the dial should be and no hands in Safari on Mac OS. The JS error from moment has gone from the JS developer console. 

Going to try rolling my local copy of analogclock.js back to the previous commit to this one

**Comment by tallnhairydave** [comment]
Rolled back to the 8th Jan commit version of analogclock.js, cleared cache in Safari, restarted home assistant. still broken. 

rolled back to the previous commit to that (31st Dec), which should work. Still broken.

Rolled back even further, still broken in Safari, but working fine in other browsers. 

Looks like Safari has had an update and it's JS version no longer supports some of the code used? The Safari release notes for the previous technology preview version does mention _Fixed Intl.DateTimeFormat#formatRange to generate the same output to Intl.DateTimeFormat#format if startDate and endDate are “practically-equal”_ 

I'm assuming that's now rolled in to the current live Safari update. Wonder if that might have caused this?

**Comment by tomasrudh** [comment]
I hope I have figured out what is going on, it seems Safari does not accept the same way the Date object is initialized as other browsers. I have changed to a different way, in hope that it works now.

**Comment by kenge1967** [comment]
I can confirm that the clock is now working i Safari as well in the IOS-app

**Comment by tallnhairydave** [comment]
Thanks Thomas! Can confirm the same as kenge1967 above - now working again in Safari and the iOS app, and safari on mobile devices. 

Great to have it back again!

**Comment by tomasrudh** [comment]
Great! Thank you for letting me know.
