### ISSUE TITLE
Week number shows " v." before week number (locale bug?)

### ISSUE THREAD

**Issue by TRusselo** [tomasrudh/analogclock#2]
I am thinking this is a locale bug?

v. ??  not sure what v stands for.
I thought this was a version number for the first 10 minutes... until I tried to get rid of it and realized its week 51 and it says v. 51
In English (us)  "v." usually means version.

We dont have a shorthand for Week.   maybe WK

![image](https://user-images.githubusercontent.com/1154815/102720639-ca440780-42b2-11eb-9ef9-08421669d745.png)

**Comment by tomasrudh** [comment]
Thanks for pointing that out, it is a locale bug. And you are right, week in Swedish is vecka, hence the 'v'. I will remove the 'v'.

**Comment by TRusselo** [comment]
tack

**Comment by tomasrudh** [comment]
Fixed in 1.3
