### ISSUE TITLE
"Invalid time" error on IOS

### ISSUE THREAD

**Issue by windsurferwill** [tomasrudh/analogclock#24]
Hi!  On iOS (iPad) I get 'invalid time' showing over the clock face.  There are no minute nor second hands.  This occurs on the HA application as well as in Chrome and Safari.  It works fine on my Windows browsers and Android app.

**Comment by tomasrudh** [comment]
Hi! There seem to be differences in how IOS interprets dates and times. Are you using dateformat and/or timeformat? If so, what do they look like? I don't have any device with IOS so I cannot test myself. Take a look at this discussion if that can give some help:
[StackOverflow](https://stackoverflow.com/questions/53137450/why-is-iphone-ios-showing-invalid-date-for-momentjs)

Regards,
Tomas

**Comment by windsurferwill** [comment]
Hi Tomas,

Thanks for the quick reply.  This is what I show if I edit the card from 
the overview screen in HA.

type: custom:analog-clock
hide_SecondHand: false
diameter: 200
color_HourHand: '#326ba8'
color_MinuteHand: '#3273a8'
color_DigitalTime: '#CCCCCC'
color_FaceDigits: '#a83832'
color_Ticks: Silver

I looked at the stackoverflow link you sent but cannot tell where I 
would look in hassio to find that code?  I looked in 
/config/config/www.community/analogclock at the analogclock.js file but 
don't see anything in there similar to the stackoverflow discussion.  
Thoughts?

Thanks,
Steve

**Comment by tomasrudh** [comment]
The thought with the link was to get some ideas about how to format date and time, but as you do not seem to use dateformat or timeformat in your configuration, is that not the problem. Unfortunately am I not sure how to troubleshoot, as I don't have an IOS device.

**Comment by windsurferwill** [comment]
Thanks Tomas, I understand.  Pardon me for such dumb questions, but do 
you know where your card code gets it's time information? I'm trying to 
figure out where to look.  I see a reference to 'ha-card' in your 
analogclock.js code but not sure it that is at all related.  Any ideas 
on where I should look?

**Comment by windsurferwill** [comment]
Another question.  I see many 'sv-SE' in calls within analogclock.js.   
Is that tied to Sweden?

**Comment by tomasrudh** [comment]
There are no dumb questions :)

The ha-card is the basis for the card layout, no connection to time in that. The time is fetched in line 33: 'new Date()'.

The 'sv-SE' is just so that I get all dates and times in a predictable format.

If you don't set the config setting 'locale', will the locale your device has, be used. Maybe you can try to set a specific locale, like : 'locale: en-US'.

**Comment by tomasrudh** [comment]
No feedback in some time, closing
