### ISSUE TITLE
[Feature Request] Color coding hours for use with kids (homework, playtime, bedtime, dinnertime]

### ISSUE THREAD

**Issue by ensey** [tomasrudh/analogclock#27]
Thank you for the work with the analog clock!

I hope this is the right way to go about the request.

I was hoping to be able to adjust the background color of the clock, based on time and perhaps on-demand timer.
My thoughts was to have a set schedule, that would enable me to color code different time-areas to certain colors, that would represent an action, that would cover the time from geetting home, and bedtime and beyond.
Something like:
15:00 - 18:00 Playtime
18:00 - 18:30 Bathtime
18:30 - 19:00 Get ready to bed
19:00 - 00:00 Sleepy time

My kids 3 years old, so we don't have homework yet - but it would be perfect for that as well.

The on-demand timer I was mentioning, would be for dinner-time.
This could either be done with a button, that turns the next 20-30 minutes into the dinnertime color - or something I could set with a setting in another card and have the length predetermined, and just input todays estimated dinnertime, so that it shows on the clock.

Thank you for reading.

**Comment by tomasrudh** [comment]
Hi ensey!

Thanks for the suggestions, the first one, setting background color based on time actually already exists, use the 'themes' setting. Something like this:
```
  themes:
  - time: 15:00-18:00
    color_background: green
  - time: 18:00-18:30
    color_background: "#0000FF"
```

The other one do I believe is a little complex for the clock, I suggest you implement that with a custom card where you set background color based on clicks on card buttons.

Hope that makes sense.

Thanks again!
/Tomas

**Comment by ensey** [comment]
Hello tomas

Thank you for answering and sorry for my slow reply.

I think you misunderstood me.
The coloration I was looking for was not the full clock face, but rather "pizza slice" coloring.
So that the triangle between  5-6, for example, is a certain color.


![step-2-of-3-after-school-hack-schecule-clock-kids-activities-blog-610x915](https://user-images.githubusercontent.com/4716832/192980393-8915b457-dcda-4365-924f-9c09e2eb7e88.jpeg)

I hope this better explains it

**Comment by tomasrudh** [comment]
I see, thanks for clarifying. However, I think that is a little too specific. If there are more interest in this feature, I might reconsider, but for now I will pass on that.

Thanks for the idea though!
/Tomas
