### ISSUE TITLE
timezone

### ISSUE THREAD

**Issue by marcobologni** [tomasrudh/analogclock#29]
Does not work with timezone
![image](https://github.com/tomasrudh/analogclock/assets/60386544/baec386b-c1d0-414c-8ce0-0fac24a0c1b7)

**Comment by tomasrudh** [comment]
Have you added moment.js to your config?
Also, try to clear the cache in your browser.

**Comment by marcobologni** [comment]
![image](https://github.com/tomasrudh/analogclock/assets/60386544/51f4a243-b991-49be-9a85-f9d92c3835c3)
Obviously cleared the cache, restarted HA and prayed that the instructions are made in an understandable way for inexperienced people who go crazy for hours on the internet looking for explanations of how to understand the instructions

**Comment by tomasrudh** [comment]
First, make sure you have moment included in your configuration. Secondly, moment is run in your browser, I have seen that it can take a couple of clearing the cache and restarting the browser. Possibly also restart Home Assistant.

I am sorry, I do not understand the text in the error message.

Could you please share the part of your section 'resources' in ui-lovelace.yaml where moment is declared?

It might work better to download moment.js and instead use the local copy, like:
```
resources:
  - url: /local/moment_2.29.1.js
    type: js
```

**Comment by marcobologni** [comment]
![1](https://github.com/tomasrudh/analogclock/assets/60386544/c5c90cff-be2c-43ef-b5d4-fba07acc47ef)
![2](https://github.com/tomasrudh/analogclock/assets/60386544/26c93977-c072-46f1-b07f-38b1617aeb6b)
![3](https://github.com/tomasrudh/analogclock/assets/60386544/034b4e5a-5224-459b-b4ce-9eac2dc05099)
![4](https://github.com/tomasrudh/analogclock/assets/60386544/4b6fbffb-1cd8-43b5-84c0-f2d8ef12dbef)
![5](https://github.com/tomasrudh/analogclock/assets/60386544/c940521a-2a55-48a0-a9f6-63aca1a93ea0)

**Comment by tomasrudh** [comment]
Unfortunately I have no experience in configuring using UI.

It seems you have moment twice, both as a URL and as local file, not sure how that plays.

Is it Italian? Again, I do not understand the texts.

**Comment by tomasrudh** [comment]
I haven't heard back in a while, I will close this issue, please come back if you need.
