### ISSUE TITLE
[Q] Use var color values?

### ISSUE THREAD

**Issue by PulsarFX** [tomasrudh/analogclock#32]
Is it possible to use color variables like `var(--secondary-text-color)`  to have the clock adapt to theme changes (light/dark) automatically?
I tried with
```
color_digitaltime: '--secondary-text-color'
color_hourhand: var(--label-badge-green)
```
but these variations have no effect.

**Comment by tomasrudh** [comment]
No, it won't work, but it is a good idea.

**Comment by tomasrudh** [comment]
I will add this to the wish list, and close this for now. Thanks for the suggestion.

**Comment by tomasrudh** [comment]
There are from version 2.0 four ways to set colors:
"green"
"#3273a8"
rgba(44,0,88,0.5)
"--secondary-text-color"
