### ISSUE TITLE
Multiple cards defaulting to the same timezone

### ISSUE THREAD

**Issue by ardoviniandrea** [tomasrudh/analogclock#38]
The purpose of this card for me is to have multiple clocks with different timezones, as I work with a very wide team and I'd like to have a visual element to see all the timezones I care about.

When I add multiple cards in my dashboard it works fine for ~30 seconds (although there is not a real consistency I can see)
<img width="811" alt="Screenshot 2024-07-30 at 18 37 34" src="https://github.com/user-attachments/assets/ab98bc2f-4143-4963-9fd3-a44a030506c5">

untill at some point it defaults all cards to one (also not always the same), untill the next refresh
<img width="804" alt="Screenshot 2024-07-30 at 18 38 30" src="https://github.com/user-attachments/assets/24ebb631-837b-477e-8d80-c0d6c1474e7f">

For completeness this is one of my cards code, they are all the same and I'm changing only the timezone
```
type: custom:analog-clock
color_HourHand: '#6461a7'
color_MinuteHand: '#6461a7'
color_secondhand: '#4e4b82'
color_FaceDigits: '#706cba'
color_DigitalTime: '#4e4b82'
color_background: '#dadaf3'
color_text: '#4e4b82'
hide_minorticks: false
hide_digitaltime: false
style_hourhand: 3
style_minutehand: 3
style_secondhand: 3
show_timezone: true
timezone: America/Los_Angeles
dateformat: mmmm dd, yyyy
timeformat: HH:MM
```

**Comment by tomasrudh** [comment]
Thanks for reporting this. I have found that settings data were leaking between instances of Analog Clock. I have just released a fix for that, lookout for an update.

Thanks again,
Tomas
