### ISSUE TITLE
Issue with me not with the clock

### ISSUE THREAD

**Issue by snug-inglenook** [tomasrudh/analogclock#4]
I really don't know how to install it. But I'd really want to try it... Can you walk me through?

**Comment by tomasrudh** [comment]
Hi, there is a great explanation by @TRusselo in issue #1, please take a look at that.

Regards,
Tomas

**Comment by snug-inglenook** [comment]
Great!

**Comment by tomasrudh** [comment]
I assume you worked it out, otherwise just create another issue or start a discussion.

/Tomas

**Comment by snug-inglenook** [comment]
You assume correctly. Works flawlessly. Thank you.
